name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        perl-version: ['5.10']
        include:
          - perl-version: '5.30'
            os: ubuntu-latest
            release-test: true
          - perl-version: '5.30'
            os: macos-latest
          - perl-version: '5.30'
            os: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry # ignored non-windows
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V

      - name: Ubuntu packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get -y update && sudo apt-get install build-essential gfortran
      - name: MacOS packages
        if: matrix.os == 'macos-latest'
        run: brew reinstall gcc

      - name: Run release tests # before others as may install useful stuff
        if: ${{ matrix.release-test }}
        env:
          RELEASE_TESTING: 1
        run: |
          cpanm -n --installdeps --with-develop .
          prove -lr xt

      - run: cpanm -n ExtUtils::MakeMaker && cpanm -n --installdeps .
      - name: Run tests (no coverage)
        if: '!matrix.coverage'
        env:
          HARNESS_OPTIONS: j4
        run: perl Makefile.PL && make test

  vm:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        vm: [freebsd-vm]
    steps:
      - uses: actions/checkout@v2
      - name: VM
        if: matrix.vm == 'freebsd-vm'
        uses: vmactions/freebsd-vm@v0.1.2
        with:
          usesh: true
          run: |
            freebsd-version
            cpanm -n ExtUtils::MakeMaker && cpanm -n --installdeps .
            perl Makefile.PL && HARNESS_OPTIONS='j4' make test
